# Generated by Django 4.2.5 on 2023-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_weekdistance_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weekdistance",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
